In [49]:
import numpy as np
import numpy.linalg as nla
import numpy.random as nrd

# Exercise 14.22

Write a program to compute the PageRank solutions by the power method using formulation (14.107).
Apply it to the network with the following connectivity,

In [33]:
# Network size
N = 6

# Connectivity
L = np.zeros((N,N))

# page 3 and 4 link to page 1
L[0,2] = 1
L[0,3] = 1

# page 1 and 6 link to page 2
L[1,0] = 1
L[1,5] = 1

# page 1, 2, 4, and 5 link to page 3
L[2,0] = 1
L[2,1] = 1
L[2,3] = 1
L[2,4] = 1

# page 6 links to page 5
L[4,5] = 1

print(L)

[[0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


# Solution

We construct the A matrix as described in the main text (the transition probability matrix for the random walk),

In [10]:
# First, let's compute the degree of connectivity of each page (to how many pages they link)
C = np.sum(L,axis=0)
D_c = np.diag(1/C)

# Then, the A matrix is defined as,
E = np.ones((N,N))
d = 0.85

A = (1-d)/N * E + d * L @ D_c

Here we define the function for converging to a stationary solution (just walk your random walk),

In [99]:
def find_stationary_solution(A,max_iter=100,eps=1e-8):
    
    N,_ = A.shape
    
    e = np.ones(N)
    p0 = nrd.rand(N)
    
    for _ in range(max_iter):
        
        p = A @ p0
        p = N * p / (e @ p)
        
        if np.sum(abs(p-p0)) < eps:
            break
            
        p0 = p

    return p

We can now obtain the stationary solution,

In [103]:
stationary = find_stationary_solution(A)

print('stationary solution = {}'.format(stationary))

stationary solution = [2.12340305 1.1161963  2.24665065 0.15       0.21375    0.15      ]


The stationary solution is indeed eigenvector of A wrt 1,

In [105]:
np.isclose(A @ stationary, stationary)

array([ True,  True,  True,  True,  True,  True])